### ISSUE TITLE
Error for Downloading

### ISSUE THREAD

**Issue by craigmate** [RobK/photobox-downloader#16]
HI
I have tried running your program on both a raspberry pi and ubuntu VM and i keep receiving the below errors

Processing album: Hazlin
/usr/local/lib/node_modules/photobox-downloader/lib/photobox.js:232
              link = pageLink.replace('&page=2&', '&page=' + i + '&');
                              ^

TypeError: Cannot read property 'replace' of undefined
    at Request._callback (/usr/local/lib/node_modules/photobox-downloader/lib/photobox.js:232:31)
    at Request.self.callback (/usr/local/lib/node_modules/photobox-downloader/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/photobox-downloader/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/photobox-downloader/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

Also when I installed it. I got some deprecation errors

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/pbdl -> /usr/local/lib/node_modules/photobox-downloader/photobox-dl.js
+ photobox-downloader@0.5.1
added 153 packages from 93 contributors in 13.333s

If anyone can point me in the right direction, that would be great.

**Comment by PhilTee** [comment]
I replaced all instances of `http://` with `https://` in photobox.js and downloads started working.

**Comment by craigmate** [comment]
Thanks for that, I changed all the settings to https and it worked.  Cheers 
It probably should be in the photobox.js but thats for the owner to decide I guess.
