### ISSUE TITLE
Error on running the script

### ISSUE THREAD

**Issue by martignonia** [RobK/photobox-downloader#18]
Hello, I'm trying to use this app but unfortunately I'm running in this error:

:Photobox domain: (www.photobox.ie) (node:5353) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
www.photobox.it
:Authentication Cookie: 
:Folder where to save albums: (albums) 
:Skip (don't download) existing files: (true) 
:Album name (leave blank to download all albums): foto
Logged into Photobox!
Starting to download all albums and photos to: /Users/aaaa/albums 
Processing album: foto
/usr/local/lib/node_modules/photobox-downloader/lib/photobox.js:232
              link = pageLink.replace('&page=2&', '&page=' + i + '&');
                              ^

TypeError: Cannot read property 'replace' of undefined
    at Request._callback (/usr/local/lib/node_modules/photobox-downloader/lib/photobox.js:232:31)
    at Request.self.callback (/usr/local/lib/node_modules/photobox-downloader/node_modules/request/request.js:185:22)
    at Request.emit (node:events:329:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/photobox-downloader/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:329:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/photobox-downloader/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:435:28)
    at IncomingMessage.emit (node:events:341:22)
    at endReadableNT (node:internal/streams/readable:1294:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

Any idea?

**Comment by vvo** [comment]
same issue here

**Comment by vvo** [comment]
For anyone cominug up here, just change all http: calls in the scripts to https:, works perfectly, thanks a lot!

**Comment by sylvain34et44** [comment]
Le mieu c’est que tu glisse la photo en bas de la page et le logiciel organise la page avec toutes tes photos. 
Au plaisir

**Comment by RobK** [comment]
Thanks for the report. I have fixed this issue and published a new version (0.5.2)
